<?php

namespace AppBundle\Repository;

/**
 * PhotosOfPhotoShootRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotosOfPhotoShootRepository extends \Doctrine\ORM\EntityRepository
{
}
