<?php

namespace AppBundle\Repository;

/**
 * PhotoShootRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoShootRepository extends \Doctrine\ORM\EntityRepository
{
}
