<?php

namespace AppBundle\Repository;

/**
 * PhotosOfProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotosOfProductRepository extends \Doctrine\ORM\EntityRepository
{
}
