<?php

namespace AppBundle\Repository;

/**
 * StatusHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusHistoryRepository extends \Doctrine\ORM\EntityRepository
{

}
