app:
    resource: '@AppBundle/Controller/'
    type: annotation

appyml:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix: /

#fos_user:
#    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

_dashboard:
    path: /
    defaults: { _controller: AppBundle:Dashboard:index }

_search:
    path: /szukaj
    defaults: { _controller: AppBundle:Search:index }

_photoSession:
    path: /sesje-zdjeciowe
    defaults: { _controller: AppBundle:PhotoSession:index }

_statusHistory:
    path: /status-history
    defaults: { _controller: AppBundle:StatusHistory:index }
