security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_PHOTOGRAPHER:  [ROLE_USER, ROLE_PHOTOGRAPHER]
        ROLE_RETOUCHER:     [ROLE_USER, ROLE_RETOUCHER]
        ROLE_WEBMASTER:     [ROLE_USER, ROLE_WEBMASTER]
        ROLE_ADMIN:         [ROLE_PHOTOGRAPHER, ROLE_RETOUCHER, ROLE_WEBMASTER]
        ROLE_SUPER_ADMIN:   ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
#            user_checker: fos_user.user_checker
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path:  ^/(css | js ),  role:  IS_AUTHENTICATED_ANONYMOUSLY  }
        - { path:  ^/(_ wdt | _profiler),  role:  IS_AUTHENTICATED_ANONYMOUSLY }
        - { path:  ^/,  role:  ROLE_USER  }
