user_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:User:edit" }
    methods:  [GET, POST]

user_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:User:delete" }
    methods:  DELETE
